
name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # run: npm install
            #- run: npm run test
            - run: docker-compose -f docker-compose.prod.yml up -d
            - run: docker exec desafio5 npm run test